### ISSUE TITLE
Can't run panda.

### ISSUE THREAD

**Issue by coke** [tadzik/panda#237] opened 2015-10-15 20:16 UTC
Update rakudo to Zürich-373-g254c1a8, install into $HOME/perl6.

Update panda to 6a649ce

Running bootstrap or rebootstrap e.g. with "perl6 bootstrap.pl", get these errors:

```
==> Bootstrapping Panda
===SORRY!===
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:16
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:26
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:36
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:42
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:48
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:54
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:61
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:68
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));
Calling make-default-ecosystem(Str) will never work with declared signature ()
at bin/panda:84
------>     my $panda = Panda.new(:ecosystem(⏏make-default-ecosystem($prefix)));

==> Please make sure that $HOME/perl6/share/perl6/site/bin is in your PATH
```

**Comment by coke** [comment] 2015-10-15 20:32
Completely nuking the install directory (which presumably had an incompatible version of Panda.pm installed) worked.

**Comment by niner** [comment] 2016-01-09 12:43
Closing since we cannot reproduce it and the whole module management in rakudo was changed in the mean time. Let's move on to new, exciting issues :)

**Closed by niner** 2016-01-09 12:43 UTC
